"""Sanitize and normalize text for speech synthesis."""

import re

def sanitize_text(text: str) -> str:
    """Sanitize text for speech synthesis and TTS use."""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"^[-*_]{3,}\s*$", "", text, flags=re.MULTILINE)
    text = re.sub(r"!\[([^\]]*)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"```[\w-]*\n([\s\S]*?)```", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = text.replace("`", "").replace("´", "")
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"^\s*[-*+]\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"^\s*(\d+)\)\s+", r"\1. ", text, flags=re.MULTILINE)
    text = re.sub(r"(?<=\n)(\d+)\)\s+", r"\1. ", text)
    text = re.sub(r"\*+", "", text)
    text = re.sub(r"~\s*(\d+)", r"about \1", text)
    text = text.replace("~", "")
    text = re.sub(r"(?<=[a-zA-Z0-9])\s*/\s*(?=[a-zA-Z0-9])", ", ", text)
    text = text.replace("/", " ").replace("\\", " ")
    text = re.sub(r"_+", " ", text)
    text = re.sub(r"(\d+)\s*[-–—]\s*(\d+)", r"\1 to \2", text)
    text = re.sub(r"\s*[-–—]{2,}\s*", ", ", text)
    text = re.sub(r"\s+[-–—]\s+", ", ", text)
    text = re.sub(r"[–—]", ", ", text)
    text = re.sub(r"(?<=[a-zA-Z0-9])-(?=[a-zA-Z0-9])", " ", text)
    text = text.replace("-", " ")
    text = re.sub(r"[\"“”«»„‟]", "", text)
    text = re.sub(r"(?<=[a-zA-Z0-9])[’\x27](?=[a-zA-Z])", "§APOS§", text)
    text = re.sub(r"[\x27‘’]", "", text)
    text = text.replace("§APOS§", "'")
    text = re.sub(r"\(([^)]+)\)", r", \1, ", text)
    text = re.sub(r"[()\[\]{}]", " ", text)
    text = re.sub(r"#(\d+)", r"number \1", text)
    text = text.replace("#", " ")
    text = re.sub(r"\s*&\s*", " and ", text)
    text = re.sub(r"(\d+)\s*%", r"\1 percent", text)
    text = text.replace("%", " percent ")
    text = re.sub(r"\s*\+\s*", " plus ", text)
    text = re.sub(r"\s*=\s*", " equals ", text)
    text = re.sub(r"[@^|<>]+", " ", text)
    text = re.sub(r"\s+([,.:;?!])", r"\1", text)
    text = re.sub(r",(\s*,)+", ",", text)
    text = re.sub(r",(\s*\.)+", ".", text)
    text = re.sub(r"\.(\s*,)+", ".", text)
    text = re.sub(r"^\s*,\s*", "", text, flags=re.MULTILINE)
    text = re.sub(r"[ \t]+", " ", text)
    text = "\n".join(line.strip() for line in text.splitlines())
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text
